### ISSUE TITLE
[Feature request] Add VAE options

### ISSUE THREAD

**Issue by JilekJosef** [Xerxemi/sdweb-auto-MBW#16]
Since VAE can affect result of the classifiers it would be good to have "add default VAE" option which would leed to overwriting base models VAEs.

**Comment by Xerxemi** [comment]
that's somewhat outside the scope of this project to be honest, it's possible to overwrite vae using another extension such as model toolkit. VAE used for scoring can be changed via the normal vae setting in webui.
