### ISSUE TITLE
[Question] What would happen if you used a different grader?

### ISSUE THREAD

**Issue by korakoe** [Xerxemi/sdweb-auto-MBW#3]
I was thinking, what if you AI image detector instead of an aesthetic grader? Or maybe both? Or an aesthetic grader that grades the anatomy instead of the overall aesthetic?

I believe it could produce some interesting merges

**Comment by Xerxemi** [comment]
This could be implemented using the classifier plugin system (there is one in scripts/classifiers) using the score(image) function.  If there was a classifier that could output a single score for this stuff I don't see why it wouldn't be possible.
