### ISSUE TITLE
Negative finetune settings

### ISSUE THREAD

**Issue by SeekerOfTheThicc** [Xerxemi/sdweb-auto-MBW#5]
So I understand most of the steps to do a negative finetune, but how do you use AMBW to subtract the model from the finetuned "bad"model, and then subsequently subtract that from the original model?  What sliders need to slide and buttons to be pushed.

**Comment by Xerxemi** [comment]
you have to use the autombw-e tab, then uncheck all boxes next to the sliders (this will turn off the "tuning" for each of those values). Then set all A sliders to 1, all B sliders to -1, using the test base a&b sliders which will change every slider along with them. Set model A to finetuned, B to original then subtract to get the extract, then A to original and B to extract to get the final model.

**Comment by SeekerOfTheThicc** [comment]
Damn I was so close.  What I didn't figure out what the checkmark boxes.

Do you have any guidance to give on making the "bad" model in dreambooth?  captions, no captions, etc?

**Comment by Xerxemi** [comment]
Captions are usually recommended with dreambooth, but you probably should use the wd tagger to generate them for variety.

To be honest, I haven't ventured too far into the negative finetuning hole, so I don't know that much, haha.

Class/regularization images can/should probably be disabled, as the training data is basically just all the model's worst parts. Don't quote me on that though.

**Comment by SeekerOfTheThicc** [comment]
Thanks for the info.  This is a fun tool to play with. Thank you, and thank you the other guy, for spending the time and sharing your work.

**Comment by jvkap** [comment]
This dont work anymore? Tried it today in the new version but this look all the bad images only lol
